repositories:
  - name: ingress-nginx
    url: "https://kubernetes.github.io/ingress-nginx"
  - name: jetstack
    url: "https://charts.jetstack.io"

releases:
  - name: ingress-nginx
    namespace: infra
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    wait: true
    timeout: 300
    values:
      - values-ingress-nginx.yaml.gotmpl
  - name: cert-manager
    namespace: infra
    chart: jetstack/cert-manager
    version: v1.14.5
    wait: true
    timeout: 300
    values:
      - values-cert.yaml.gotmpl
