apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-service
  namespace: argocd
  labels:
     environment: {{ .Values.environment }}
     location: {{ .Values.location }}
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    helm:
        releaseName: site-service
        valueFiles:
        - values-live-ne.yaml
    path: devops/iac/k8s/argocd/charts/site-service
    repoURL: https://github.com/duumbi/duumbi.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
