resources:
  - kind: folder
    selector:
      query: 'true'
      folders:
        - path: applications/*
    port:
      entity:
        mappings:
          identifier: .folder.name
          title: .folder.name
          blueprint: '"web_application"'
          properties:
            url: >-
              .repo.html_url + "/tree/" + .repo.default_branch  + "/" +
              .folder.path
            readme: file://README.md