default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages: [pre-commit]

repos:
# BASIC CONF FOR ALL PRE-COMMITS REPO TYPE
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Git style
      - id: check-added-large-files
        args: [--maxkb=100]
      - id: check-merge-conflict
      - id: forbid-submodules

      # Common errors
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Cross platform
      - id: mixed-line-ending
        args: [--fix=auto]

       # Security
      - id: detect-private-key
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
# SPECIFIC CONF FOR TERRAFORM MODULE REPOSITORIES
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-write=true
      - id: terraform_tflint
        files: \.tf$
        args:
            - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_trivy