/* tslint:disable */
/* eslint-disable */
/**
 * Duumbi Site Service API v1
 * This is a Duumbi Site Service API documentation. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@duumbi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     *
     * @type {string}
     * @memberof Profile
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Profile
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof Profile
     */
    picture?: string;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): value is Profile {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'picture': json['picture'] == null ? undefined : json['picture'],
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value == null) {
        return value;
    }
    return {

        'name': value['name'],
        'email': value['email'],
        'picture': value['picture'],
    };
}

