# --------------------------------------------------------------------------------------------------
# Spring properties
# --------------------------------------------------------------------------------------------------
spring:
  application:
    name: site-service
  main:
    banner-mode: "off"

# --------------------------------------------------------------------------------------------------
# Server properties
# --------------------------------------------------------------------------------------------------
server:
  error:
    include-message: always

# --------------------------------------------------------------------------------------------------
# Management
# --------------------------------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      probes:
        enabled: true
      show-details: ALWAYS
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# --------------------------------------------------------------------------------------------------
# Application properties
# --------------------------------------------------------------------------------------------------
application:
  environment: ${ENVIRONMENT}

# --------------------------------------------------------------------------------------------------
# Logging properties
# --------------------------------------------------------------------------------------------------
logging:
  level:
    root: info
    org:
      springframework: info
    io:
      duumbi: info