# --------------------------------------------------------------------------------------------------
# Spring properties
# --------------------------------------------------------------------------------------------------
spring:
  application:
    name: site-service
  main:
    banner-mode: "off"
  cache:
    cache-names: instruments
    type: hazelcast

# --------------------------------------------------------------------------------------------------
# Server properties
# --------------------------------------------------------------------------------------------------
server:
  port: 3010
  error:
    include-message: always

# --------------------------------------------------------------------------------------------------
# Management
# --------------------------------------------------------------------------------------------------
management:
  server:
    port: 3011
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      probes:
        enabled: true
      show-details: ALWAYS
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# --------------------------------------------------------------------------------------------------
# Okta properties
# --------------------------------------------------------------------------------------------------
okta:
  oauth2:
    issuer: ${AUTH_SITE_API_ISSUER}
    audience: ${AUTH_SITE_API_AUDIENCE}

auth0:
  management:
    api:
      domain: ${AUTH_MANAGEMENT_API_DOMAIN}
      client-id: ${AUTH_MANAGEMENT_API_CLIENT_ID}
      client-secret: ${AUTH_MANAGEMENT_API_CLIENT_SECRET}
      identifier: ${AUTH_MANAGEMENT_API_IDENTIFIER}

# --------------------------------------------------------------------------------------------------
# Application properties
# --------------------------------------------------------------------------------------------------
application:
  environment: ${SERVICE_ENVIRONMENT}
  client-origin-url: ${CLIENT_ORIGIN_URL}

# --------------------------------------------------------------------------------------------------
# Logging properties
# --------------------------------------------------------------------------------------------------
logging:
  level:
    root: warn
    org:
      springframework: warn
    io:
      duumbi: info