# --------------------------------------------------------------------------------------------------
# Spring properties
# --------------------------------------------------------------------------------------------------
spring:
  application:
    name: site-service
  main:
    banner-mode: "off"

# --------------------------------------------------------------------------------------------------
# Server properties
# --------------------------------------------------------------------------------------------------
server:
  port: 3010
  error:
    include-message: always

# --------------------------------------------------------------------------------------------------
# Management
# --------------------------------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      probes:
        enabled: true
      show-details: ALWAYS
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# --------------------------------------------------------------------------------------------------
# Okta properties
# --------------------------------------------------------------------------------------------------
okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: ${AUTH_SITE_API_ISSUER}
    # Replace with the API Identifier for your Auth0 API.
    audience: ${AUTH_SITE_API_AUDIENCE}

# --------------------------------------------------------------------------------------------------
# Application properties
# --------------------------------------------------------------------------------------------------
application:
  environment: ${SERVICE_ENVIRONMENT}
  client-origin-url: ${CLIENT_ORIGIN_URL}

# --------------------------------------------------------------------------------------------------
# Logging properties
# --------------------------------------------------------------------------------------------------
logging:
  level:
    root: warn
    org:
      springframework: warn
    io:
      duumbi: info