openapi: 3.0.0
info:
  title: Duumbi Site Service API v1
  description: "This is a Duumbi Site Service API documentation. API has resource-oriented\
    \ URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses."
  contact:
    name: Duumbi
    url: https://duumbi.io/
    email: mail@duumbi.io
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/duumbi/site/1.0.0
  description: SwaggerHub API Auto Mocking
- url: "https://api.site-{location}.duumbi.io/{basePath}"
  description: The production API server
  variables:
    location:
      default: ne
      enum:
      - ne
      - eu
    basePath:
      default: v1
tags:
- name: profile
  description: Profile operations
paths:
  /profiles/{id}:
    get:
      tags:
      - profile
      summary: Retrieve a user profile.
      operationId: GetProfile
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: User successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        "404":
          description: Non-existent resource is requested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Profile:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        picture:
          type: string
    Error:
      required:
      - message
      type: object
      properties:
        message:
          type: string
      example:
        message: The request is malformed.
  responses:
    BadRequest:
      description: The request is malformed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Authorization information is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Authenticated user doesn't have access to the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Non-existent resource is requested.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
