app:
  environment: live
  location: ne
  replicaCount: 1
  type: service
  container:
    image: arm64v8/nginx
    tag: 1.25.5
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

ingress:
  host: api.site-ne.duumbi.io

config:
  name: config.yml
