apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%v-configmap" .Chart.Name }}
  labels:
     {{- include "service.labels" . | nindent 4 }}
data:
  {{ .Values.config.name }}: |
  {{- $path := ( printf "config/%v/config.yml" .Values.app.environment ) }}
  {{- .Files.Get $path | nindent 4 }}