cluster: https://kubernetes.default.svc
project: duumbi
namespace: duumbi
environment: live
location: ne

host:
  argo: argocd.infra-ne.duumbi.io
  site-api: api.site-ne.duumbi.io
  duumbi-api: api.duumbi-ne.duumbi.io
