apiVersion: v1
kind: Secret
metadata:
  name: duumbi-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  type: $GITHUB_TYPE_B64
  project: $GITHUB_PROJECT_B64
  url: $GITHUB_URL_B64
  githubAppID: $GITHUB_APP_ID_B64
  githubAppInstallationID: $GITHUB_APP_INSTALLATION_ID_B64
  githubAppPrivateKey: $GITHUB_APP_PRIVATE_KEY_B64

