/* tslint:disable */
/* eslint-disable */
/**
 * Duumbi Site Service API v1
 * This is a Duumbi Site Service API documentation. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@duumbi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Profile,
} from '../models/index';
import {
    ProfileFromJSON,
    ProfileToJSON,
} from '../models/index';

export interface GetProfileRequest {
    id: string;
}

/**
 *
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     * Retrieve a user profile.
     */
    async getProfileRaw(requestParameters: GetProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profiles/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Retrieve a user profile.
     */
    async getProfile(requestParameters: GetProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.getProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
