apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  url: $ARGO_URL
  oidc.config: |
      name: Azure
      issuer: https://login.microsoftonline.com/$AZURE_TENANT_ID/v2.0
      clientID: $ARGO_SSO_CLIENT_ID
      clientSecret: $oidc.azure.clientSecret
      requestedIDTokenClaims:
          groups:
              essential: true
      requestedScopes:
          - openid
          - profile
          - email
