name: App - Web Application

trigger:
  - none

pr:
  autoCancel: true # Automatically cancel previous runs when a new run is triggered
  branches:
    include:
      - "*"
  paths:
    include:
      - "applications/app-web-application/**"

variables:
  system.debug: "false" # Enable or disable debug mode

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:
  - stage: deploy_stage
    displayName: Deploy to stage
    jobs:
      - job: build_and_deploy_job
        displayName: Build and deploy Job
        condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
        pool:
          vmImage: "ubuntu-latest"
        timeoutInMinutes: 2 # Cancel the job if it hasn't completed after 60 minutes
        variables:
          group: stg-app-web-application

        steps:
          - script: |
              # Read the Node.js version from .nvmrc
              NODE_VERSION=$(cat .nvmrc)
              echo "##vso[task.setvariable variable=NODE_VERSION]$NODE_VERSION"
            displayName: 'Read Node.js version from .nvmrc'

          - task: UseNode@1
            inputs:
              version: '$(NODE_VERSION)'
            displayName: 'Use Node.js version from .nvmrc'

          - script: |
              node -v
              npm -v
            displayName: 'Check Node.js and npm version'

          - script: |
              npm install
              npm run codegen
            displayName: 'Install dependencies'

          # - template: doppler/steps/install-doppler-cli.yml@templates
          #   parameters:
          #     DOPPLER_TOKEN: $(DOPPLER_TOKEN)

          # - template: newrelic/steps/insert-newrelic-js-agent.yml@templates
          #   parameters:
          #     AGENT_FILE: $(NEW_RELIC_AGENT)
          #     SOURCES_DIRECTORY: '$(Build.SourcesDirectory)'
          #     TARGET_FOLDER: 'applications/app-web-application/public/js'
