name: $(BuildDefinitionName) - $(date:yyyyMMdd)$(rev:.r)

trigger:
  - none

pr:
  autoCancel: true # Automatically cancel previous runs when a new run is triggered
  branches:
    include:
      - "*"
  paths:
    include:
      - "services/app-service/**"

variables:
  system.debug: "false" # Enable or disable debug mode

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:
  - stage: BuildAndPush
    displayName: Build and Push stage
    jobs:
      - job: BuildAndJob
        displayName: Build and Push Job
        condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
        pool:
          vmImage: "ubuntu-latest"
        timeoutInMinutes: 10 # Cancel the job if it hasn't completed after 60 minutes
        variables:
          group: app-service
        steps:
          - task: Docker@2
            displayName: Login
            inputs:
              command: 'login'
              containerRegistry: '$(DOCKER_REGISTRY_SERVICE_CONNECTION)'
          - script: |
              DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
              echo $DOCKER_CONFIG
              docker info
              mkdir -vp $DOCKER_CONFIG/cli-plugins/
              ARCH=amd64
              BUILDX_URL=$(curl -s https://raw.githubusercontent.com/docker/actions-toolkit/main/.github/buildx-lab-releases.json | jq -r ".latest.assets[] | select(endswith(\"linux-$ARCH\"))")
              echo $BUILDX_URL
              curl --silent -L --output $DOCKER_CONFIG/cli-plugins/docker-buildx $BUILDX_URL
              chmod a+x $DOCKER_CONFIG/cli-plugins/docker-buildx
              docker info
              ls -la $DOCKER_CONFIG/cli-plugins/
              docker buildx create --use --driver cloud hgahub/default
            displayName: 'Create a instance of the cloud builder'