name: App - Web Application

trigger:
  - none

pr:
  branches:
    include:
      - "*"
  paths:
    include:
      - "applications/app-web-application/**"

variables:
  system.debug: "false" # Enable or disable debug mode

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:
  - stage: deploy_stage
    displayName: Deploy to stage
    jobs:
      - job: build_and_deploy_job
        displayName: Build and deploy Job
        condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
        pool:
          vmImage: "ubuntu-latest"
        variables:
          group: stg-app-web-application

        steps:
          - template: doppler/steps/install-doppler-cli.yml@templates

          - script: |
              doppler configs get
            env:
              DOPPLER_TOKEN: $(DOPPLER_TOKEN)
            displayName: Doppler CLI

          - template: newrelic/steps/insert-newrelic-js-agent.yml@templates
            parameters:
              AGENT_FILE: $(NEW_RELIC_AGENT)
              SOURCES_DIRECTORY: '$(Build.SourcesDirectory)'
              TARGET_FOLDER: 'applications/app-web-application/public/js'
