name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - none

pr:
  autoCancel: true # Automatically cancel previous runs when a new run is triggered
  branches:
    include:
      - "*"
  paths:
    include:
      - "applications/app-web-application/**"

variables:
  system.debug: "false" # Enable or disable debug mode
  APP_WEB_APPLICATION_RELATIVE_PATH: 'applications/app-web-application'
  APP_WEB_APPLICATION_PATH: '$(Build.SourcesDirectory)/$(APP_WEB_APPLICATION_RELATIVE_PATH)'

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:
  - stage: Staging
    displayName: Staging
    jobs:
      - job: BuildAndDeployStagingJob
        displayName: Build and Deploy Staging Job
        condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
        pool:
          vmImage: "ubuntu-latest"
        timeoutInMinutes: 2 # Cancel the job if it hasn't completed after 60 minutes
        variables:
          group: stg-app-web-application

        steps:
          - template: node/steps/qa.yml@templates
            parameters:
              SOURCES_DIRECTORY: $(APP_WEB_APPLICATION_PATH)

          - template: doppler/steps/install-doppler-cli.yml@templates
            parameters:
              DOPPLER_TOKEN: $(DOPPLER_TOKEN)

          - template: newrelic/steps/insert-newrelic-js-agent.yml@templates
            parameters:
              AGENT_FILE: $(NEW_RELIC_AGENT)
              SOURCES_DIRECTORY: $(APP_WEB_APPLICATION_PATH)
              TARGET_FOLDER: 'public/js'

          - template: node/steps/build.yml@templates
            parameters:
              SOURCES_DIRECTORY: $(APP_WEB_APPLICATION_PATH)

          - task: AzureStaticWebApp@0
            inputs:
              deployment_environment: staging
              skip_app_build: true
              skip_api_build: true
              azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
              app_location: $(APP_WEB_APPLICATION_RELATIVE_PATH)/dist
              api_location: ''
              output_location: ''
              build_timeout_in_minutes: 5

