name: App - Web Application

trigger:
  - none

pr:
  autoCancel: true # Automatically cancel previous runs when a new run is triggered
  branches:
    include:
      - "*"
  paths:
    include:
      - "applications/app-web-application/**"

variables:
  system.debug: "false" # Enable or disable debug mode
  APP_WEB_APPLICATION_PATH: '$(Build.SourcesDirectory)/applications/app-web-application'

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:
  - stage: deploy_stage
    displayName: Deploy to stage
    jobs:
      - job: build_and_deploy_job
        displayName: Build and deploy Job
        condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
        pool:
          vmImage: "ubuntu-latest"
        timeoutInMinutes: 2 # Cancel the job if it hasn't completed after 60 minutes
        variables:
          group: stg-app-web-application

        steps:
          - template: node/steps/qa.yml@templates
            parameters:
              SOURCES_DIRECTORY: $(APP_WEB_APPLICATION_PATH)

          - template: doppler/steps/install-doppler-cli.yml@templates
            parameters:
              DOPPLER_TOKEN: $(DOPPLER_TOKEN)

          - template: newrelic/steps/insert-newrelic-js-agent.yml@templates
            parameters:
              AGENT_FILE: $(NEW_RELIC_AGENT)
              SOURCES_DIRECTORY: $(APP_WEB_APPLICATION_PATH)
              TARGET_FOLDER: 'public/js'

          - template: node/steps/build.yml@templates
            parameters:
              SOURCES_DIRECTORY: $(APP_WEB_APPLICATION_PATH)
