name: App - Web Application

trigger:
  - none

pr:
  branches:
    include:
      - "*"
  paths:
    include:
      - "applications/app-web-application/**"

variables:
  system.debug: "false" # Enable or disable debug mode

stages:
  - stage: deploy_stage
    displayName: Deploy to stage
    jobs:
      - job: build_and_deploy_job
        displayName: Build and deploy Job
        condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
        pool:
          vmImage: "ubuntu-latest"
        variables:
          - group: doppler-app-web-application
        steps:
          - script: |
              (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh
            displayName: Install Doppler CLI
          - script: doppler configs get
            displayName: Build
            env:
              DOPPLER_TOKEN: $(DOPPLER_TOKEN)
          - bash: echo '$(Build.Reason)'
            displayName: Set new variable value
